version: '3'
services:
    currency:
        build: 
            context: .
            dockerfile: Dockerfile
        image: currency
        env_file:
            - .env
        depends_on:
            - mysql
        networks:
            - currency
        ports:
            - "1335:1335"

    mysql:
        image: 'mysql:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - 'currencymysql:/var/lib/mysql'
        networks:
            - currency
        healthcheck:
            test: [ "CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}" ]
            retries: 3
            timeout: 5s
networks:
    currency:
        driver: bridge
volumes:
    currencymysql:
        driver: local
